### ISSUE TITLE
How do I get it mecrisp-stellaris installed on an nRF52832 in the first place?

### ISSUE THREAD

**Issue by rabbithat** [juju2013/nrf52-forth-lib#1]
It looks as though your libraries assume that mecrisp-stellaris is already running on an nRF52832.   Is there a published .hex file somewhere for that.  If not, how is it done?

**Comment by juju2013** [comment]
There's a nRF52832 port of mecrisp under review by Matthias:

https://github.com/juju2013/mecrisp-stellaris/tree/nrf52

**Comment by juju2013** [comment]
I'm doing a massive rewrite in converting this to iomodule (kind of wordlist) but I've still some wired issue... hopefully I can publish the new code in a few days/weeks.
